//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRM_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Review = new HashSet<Review>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string about { get; set; }
        public string logo { get; set; }
        public int popularity { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<Review> Review { get; set; }
    }
}
