//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRM_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_company { get; set; }
        public int rate { get; set; }
        public string pros { get; set; }
        public string cons { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
